apiVersion: v1
kind: Service
metadata:
  name: personal-finance-app-service
spec:
  selector:
    app: personal-finance-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4444
  type: LoadBalancer